# Generated by Django 5.2.16 on 2026-07-24 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name of the vocabulary; its slug is derived from this.', max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Optional explanation of what this vocabulary covers.', verbose_name='description')),
                ('slug', models.SlugField(allow_unicode=True, help_text='URL-safe identifier derived from the name; unique across all vocabularies.', max_length=255, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'vocabulary',
                'verbose_name_plural': 'vocabularies',
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Human-readable preferred label; the slug is derived from this.', max_length=255, verbose_name='preferred label')),
                ('slug', models.SlugField(allow_unicode=True, help_text='URL-safe identifier derived from the label; unique within its vocabulary.', max_length=255, verbose_name='slug')),
                ('scheme', models.ForeignKey(help_text='The vocabulary this concept belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='controlled_vocabularies.conceptscheme', verbose_name='vocabulary')),
            ],
            options={
                'verbose_name': 'concept',
                'verbose_name_plural': 'concepts',
                'constraints': [models.UniqueConstraint(fields=('scheme', 'slug'), name='unique_concept_slug_per_scheme')],
            },
        ),
    ]
