# Generated by Django 5.2.16 on 2026-07-24 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabularies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='slug_is_manual',
            field=models.BooleanField(default=False, help_text='Whether the slug was set explicitly rather than derived from the label. A manual slug is left untouched when the label later changes.', verbose_name='slug set manually'),
        ),
        migrations.AddField(
            model_name='conceptscheme',
            name='default_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('de', 'German'), ('fr', 'French')], help_text="The language whose preferred label anchors this vocabulary's concepts' identity. Leave blank to fall back to the application's configured default language.", max_length=16, verbose_name='default language'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='label',
            field=models.CharField(help_text="The preferred label in the vocabulary's effective default language. It is the concept's identity anchor: the slug is derived from it, and preferred labels in other languages are held as separate labels.", max_length=255, verbose_name='preferred label'),
        ),
        migrations.CreateModel(
            name='ConceptNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'German'), ('fr', 'French')], help_text="The language this note is written in, from the application's configured languages.", max_length=16, verbose_name='language')),
                ('kind', models.CharField(choices=[('definition', 'definition'), ('scope', 'scope note'), ('example', 'example'), ('editorial', 'editorial note'), ('history', 'history note'), ('change', 'change note'), ('note', 'note')], help_text='Which SKOS documentary property this note fills — its definition, a scope note, an example, and so on.', max_length=16, verbose_name='kind')),
                ('value', models.TextField(help_text='The note text, as it reads in this language.', verbose_name='value')),
                ('concept', models.ForeignKey(help_text='The concept this note describes.', on_delete=django.db.models.deletion.CASCADE, related_name='concept_notes', to='controlled_vocabularies.concept', verbose_name='concept')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
                'ordering': ('language', 'kind'),
            },
        ),
        migrations.CreateModel(
            name='ConceptLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'German'), ('fr', 'French')], help_text="The language this label is written in, from the application's configured languages.", max_length=16, verbose_name='language')),
                ('kind', models.CharField(choices=[('preferred', 'preferred'), ('alternative', 'alternative'), ('hidden', 'hidden')], help_text="Whether this is the language's preferred label or an alternative or hidden one.", max_length=16, verbose_name='kind')),
                ('text', models.CharField(help_text='The label text, as it reads in this language.', max_length=255, verbose_name='text')),
                ('concept', models.ForeignKey(help_text='The concept this label names.', on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='controlled_vocabularies.concept', verbose_name='concept')),
            ],
            options={
                'verbose_name': 'label',
                'verbose_name_plural': 'labels',
                'ordering': ('language', 'kind', 'text'),
                'indexes': [models.Index(fields=['language', 'kind', 'text'], name='cv_label_lang_kind_text_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'preferred')), fields=('concept', 'language'), name='one_preferred_label_per_language')],
            },
        ),
    ]
