# Generated by Django 5.2.16 on 2026-07-24 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabularies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='label',
            field=models.CharField(help_text="The preferred label in the vocabulary's effective default language. It is the concept's identity anchor: the slug is derived from it, and preferred labels in other languages are held as separate labels.", max_length=255, verbose_name='preferred label'),
        ),
        migrations.CreateModel(
            name='ConceptLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'German'), ('fr', 'French')], help_text="The language this label is written in, from the application's configured languages.", max_length=16, verbose_name='language')),
                ('kind', models.CharField(choices=[('preferred', 'preferred'), ('alternative', 'alternative'), ('hidden', 'hidden')], help_text="Whether this is the language's preferred label or an alternative or hidden one.", max_length=16, verbose_name='kind')),
                ('text', models.CharField(help_text='The label text, as it reads in this language.', max_length=255, verbose_name='text')),
                ('concept', models.ForeignKey(help_text='The concept this label names.', on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='controlled_vocabularies.concept', verbose_name='concept')),
            ],
            options={
                'verbose_name': 'label',
                'verbose_name_plural': 'labels',
                'ordering': ('language', 'kind', 'text'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'preferred')), fields=('concept', 'language'), name='one_preferred_label_per_language')],
            },
        ),
    ]
