# Generated by Django 5.2.16 on 2026-07-23 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabularies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='controlled_vocabularies.conceptscheme')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scheme', 'slug'), name='unique_concept_slug_per_scheme')],
            },
        ),
    ]
