# Generated by Django 5.2.16 on 2026-07-24 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabularies', '0002_multilingual_concepts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('broader', 'broader'), ('related', 'related')], help_text='The kind of link: a broader/narrower hierarchy edge, or a symmetric related association.', max_length=16, verbose_name='kind')),
                ('source', models.ForeignKey(help_text='One end of the relation. For a broader link this is the narrower (child) concept; for a related link it is the lower-numbered of the pair.', on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_source', to='controlled_vocabularies.concept', verbose_name='source concept')),
                ('target', models.ForeignKey(help_text='The other end of the relation. For a broader link this is the broader (parent) concept; for a related link it is the higher-numbered of the pair.', on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_target', to='controlled_vocabularies.concept', verbose_name='target concept')),
            ],
            options={
                'verbose_name': 'concept relation',
                'verbose_name_plural': 'concept relations',
                'ordering': ('source', 'kind', 'target'),
                'indexes': [models.Index(fields=['target', 'kind'], name='cv_relation_target_kind_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'target', 'kind'), name='unique_concept_relation'), models.CheckConstraint(condition=models.Q(('source', models.F('target')), _negated=True), name='concept_relation_not_self')],
            },
        ),
    ]
