# Generated by Django 5.2.16 on 2026-07-23 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabularies', '0002_concept'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concept',
            options={'verbose_name': 'concept', 'verbose_name_plural': 'concepts'},
        ),
        migrations.AlterModelOptions(
            name='conceptscheme',
            options={'verbose_name': 'vocabulary', 'verbose_name_plural': 'vocabularies'},
        ),
        migrations.AlterField(
            model_name='concept',
            name='label',
            field=models.CharField(help_text='Human-readable preferred label; the slug is derived from this.', max_length=255, verbose_name='preferred label'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='scheme',
            field=models.ForeignKey(help_text='The vocabulary this concept belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='controlled_vocabularies.conceptscheme', verbose_name='vocabulary'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='URL-safe identifier derived from the label; unique within its vocabulary.', max_length=255, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='conceptscheme',
            name='description',
            field=models.TextField(blank=True, help_text='Optional explanation of what this vocabulary covers.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='conceptscheme',
            name='name',
            field=models.CharField(help_text='Human-readable name of the vocabulary; its slug is derived from this.', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='conceptscheme',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='URL-safe identifier derived from the name; unique across all vocabularies.', max_length=255, unique=True, verbose_name='slug'),
        ),
    ]
