# Generated by Django 5.2.16 on 2026-07-24 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabularies', '0002_alter_concept_label_conceptlabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'German'), ('fr', 'French')], help_text="The language this note is written in, from the application's configured languages.", max_length=16, verbose_name='language')),
                ('kind', models.CharField(choices=[('definition', 'definition'), ('scope', 'scope note'), ('example', 'example'), ('editorial', 'editorial note'), ('history', 'history note'), ('change', 'change note'), ('note', 'note')], help_text='Which SKOS documentary property this note fills — its definition, a scope note, an example, and so on.', max_length=16, verbose_name='kind')),
                ('value', models.TextField(help_text='The note text, as it reads in this language.', verbose_name='value')),
                ('concept', models.ForeignKey(help_text='The concept this note describes.', on_delete=django.db.models.deletion.CASCADE, related_name='concept_notes', to='controlled_vocabularies.concept', verbose_name='concept')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
                'ordering': ('language', 'kind'),
            },
        ),
    ]
