# Generated by Django 5.2.16 on 2026-07-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabularies', '0003_conceptnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptscheme',
            name='default_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('de', 'German'), ('fr', 'French')], help_text="The language whose preferred label anchors this vocabulary's concepts' identity. Leave blank to fall back to the application's configured default language.", max_length=16, verbose_name='default language'),
        ),
    ]
