# Generated by Django 5.2.16 on 2026-07-25 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabularies', '0003_conceptrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The human-readable name of the collection. Its slug is derived automatically from this.', max_length=255, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, help_text='A URL-safe identifier derived automatically from the name. A slug must be unique within a given vocabulary.', max_length=255, verbose_name='slug')),
                ('ordered', models.BooleanField(default=False, help_text="Whether the collection's members carry a deliberate sequence (a SKOS ordered collection). An unordered collection is a plain set.", verbose_name='ordered')),
                ('scheme', models.ForeignKey(help_text='The vocabulary this collection belongs to. Its members are concepts of this vocabulary.', on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='controlled_vocabularies.conceptscheme', verbose_name='vocabulary')),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'collections',
            },
        ),
        migrations.CreateModel(
            name='CollectionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, help_text="The member's place in an ordered collection's sequence. Meaningful only when the collection is ordered; ignored otherwise.", verbose_name='position')),
                ('collection', models.ForeignKey(help_text='The collection this membership belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='controlled_vocabularies.collection', verbose_name='collection')),
                ('concept', models.ForeignKey(help_text="The member concept. It must belong to the collection's own vocabulary.", on_delete=django.db.models.deletion.CASCADE, related_name='collection_memberships', to='controlled_vocabularies.concept', verbose_name='concept')),
            ],
            options={
                'verbose_name': 'collection member',
                'verbose_name_plural': 'collection members',
                'ordering': ('collection', 'position', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('scheme', 'slug'), name='unique_collection_slug_per_scheme'),
        ),
        migrations.AddIndex(
            model_name='collectionmember',
            index=models.Index(fields=['collection', 'position'], name='cv_collection_member_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='collectionmember',
            constraint=models.UniqueConstraint(fields=('collection', 'concept'), name='unique_collection_member'),
        ),
    ]
