# Generated by Django 5.2.16 on 2026-08-03 13:40

import controlled_vocabularies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabularies', '0004_collection_collectionmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='static_uri',
            field=models.CharField(blank=True, help_text="The identifier once it is fixed — assigned by this collection's publisher, or frozen when its vocabulary is published — held exactly as given and never recomputed after that. Leave blank while this collection is authored here: its identifier is computed from this site's address until then.", max_length=500, null=True, validators=[controlled_vocabularies.models.validate_static_uri], verbose_name='static URI'),
        ),
        migrations.AddField(
            model_name='concept',
            name='static_uri',
            field=models.CharField(blank=True, help_text="The identifier once it is fixed — assigned by this concept's publisher, or frozen when its vocabulary is published — held exactly as given and never recomputed after that. Leave blank while this concept is authored here: its identifier is computed from this site's address until then.", max_length=500, null=True, validators=[controlled_vocabularies.models.validate_static_uri], verbose_name='static URI'),
        ),
        migrations.AddField(
            model_name='conceptscheme',
            name='static_uri',
            field=models.CharField(blank=True, help_text="The identifier once it is fixed — assigned by this vocabulary's publisher, or frozen when this vocabulary is published — held exactly as given and never recomputed after that. Leave blank while this vocabulary is authored here: its identifier is computed from this site's address until then.", max_length=500, null=True, validators=[controlled_vocabularies.models.validate_static_uri], verbose_name='static URI'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(condition=models.Q(('static_uri__isnull', False)), fields=('static_uri',), name='collection_static_uri_unique'),
        ),
        migrations.AddConstraint(
            model_name='concept',
            constraint=models.UniqueConstraint(condition=models.Q(('static_uri__isnull', False)), fields=('static_uri',), name='concept_static_uri_unique'),
        ),
        migrations.AddConstraint(
            model_name='conceptscheme',
            constraint=models.UniqueConstraint(condition=models.Q(('static_uri__isnull', False)), fields=('static_uri',), name='conceptscheme_static_uri_unique'),
        ),
    ]
