# Generated by Django 5.2.16 on 2026-07-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabularies', '0004_conceptscheme_default_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='slug_is_manual',
            field=models.BooleanField(default=False, help_text='Whether the slug was set explicitly rather than derived from the label. A manual slug is left untouched when the label later changes.', verbose_name='slug set manually'),
        ),
    ]
