# Generated by Django 5.2.16 on 2026-08-03 10:35

import controlled_vocabularies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabularies', '0004_collection_collectionmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='permanent_uri',
            field=models.CharField(blank=True, help_text="The identifier assigned by this collection's publisher, held exactly as given. Fixed once set. Leave blank for a collection authored here, which reports the identifier composed from this site's address instead.", max_length=500, null=True, validators=[controlled_vocabularies.models.validate_permanent_uri], verbose_name='permanent URI'),
        ),
        migrations.AddField(
            model_name='concept',
            name='permanent_uri',
            field=models.CharField(blank=True, help_text="The identifier assigned by this concept's publisher, held exactly as given. Fixed once set. Leave blank for a concept authored here, which reports the identifier composed from this site's address instead.", max_length=500, null=True, validators=[controlled_vocabularies.models.validate_permanent_uri], verbose_name='permanent URI'),
        ),
        migrations.AddField(
            model_name='conceptscheme',
            name='permanent_uri',
            field=models.CharField(blank=True, help_text="The identifier assigned by this vocabulary's publisher, held exactly as given. Fixed once set. Leave blank for a vocabulary authored here, which reports the identifier composed from this site's address instead.", max_length=500, null=True, validators=[controlled_vocabularies.models.validate_permanent_uri], verbose_name='permanent URI'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(condition=models.Q(('permanent_uri__isnull', False)), fields=('permanent_uri',), name='collection_permanent_uri_unique'),
        ),
        migrations.AddConstraint(
            model_name='concept',
            constraint=models.UniqueConstraint(condition=models.Q(('permanent_uri__isnull', False)), fields=('permanent_uri',), name='concept_permanent_uri_unique'),
        ),
        migrations.AddConstraint(
            model_name='conceptscheme',
            constraint=models.UniqueConstraint(condition=models.Q(('permanent_uri__isnull', False)), fields=('permanent_uri',), name='conceptscheme_permanent_uri_unique'),
        ),
    ]
