# Generated by Django 5.2.16 on 2026-07-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabularies', '0005_concept_slug_is_manual'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='conceptlabel',
            index=models.Index(fields=['language', 'kind', 'text'], name='cv_label_lang_kind_text_idx'),
        ),
    ]
