# Generated by Django 5.2.16 on 2026-08-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("controlled_vocabularies", "0006_conceptscheme_slug_is_manual"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="slug_is_manual",
            field=models.BooleanField(
                default=False,
                help_text="Whether the slug was set explicitly rather than derived from the name. A manual slug is left untouched when the name later changes.",
                verbose_name="slug set manually",
            ),
        ),
    ]
