# Generated by Django 5.2.16 on 2026-08-11 14:20

import controlled_vocabularies.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controlled_vocabularies', '0007_collection_slug_is_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The artifact's catalogue name.", max_length=255, verbose_name='name')),
                ('mineral', controlled_vocabularies.fields.ConceptField(blank=True, help_text='The mineral this artifact is classified as, if known.', null=True, verbose_name='mineral', vocabulary='mineral')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The sample's catalogue name.", max_length=255, verbose_name='name')),
                ('mineral', controlled_vocabularies.fields.ConceptField(blank=True, help_text='The mineral this sample is classified as, if known.', null=True, related_name='samples', verbose_name='mineral', vocabulary='mineral')),
            ],
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The specimen's catalogue name.", max_length=255, verbose_name='name')),
                ('rock_type', controlled_vocabularies.fields.ConceptField(help_text='The rock type this specimen is classified as.', verbose_name='rock type', vocabulary='rock-type')),
            ],
        ),
    ]
