# Generated by Django 5.2.16 on 2026-08-12 10:24

from django.db import migrations, models

import controlled_vocabularies.fields


class Migration(migrations.Migration):
    dependencies = [
        ("controlled_vocabularies", "0007_collection_slug_is_manual"),
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deposit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="The deposit's catalogue name.", max_length=255, verbose_name="name"),
                ),
                (
                    "rock_types",
                    controlled_vocabularies.fields.ConceptsField(
                        help_text="The rock types present at this deposit.",
                        verbose_name="rock types",
                        vocabulary=("rock-type",),
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="The survey's catalogue name.", max_length=255, verbose_name="name"),
                ),
                (
                    "primary_minerals",
                    controlled_vocabularies.fields.ConceptsField(
                        help_text="The minerals this survey primarily targets.",
                        related_name="+",
                        verbose_name="primary minerals",
                        vocabulary=("mineral",),
                    ),
                ),
                (
                    "secondary_minerals",
                    controlled_vocabularies.fields.ConceptsField(
                        help_text="The minerals this survey secondarily targets.",
                        related_name="+",
                        verbose_name="secondary minerals",
                        vocabulary=("mineral",),
                    ),
                ),
            ],
        ),
    ]
