# Generated by Django 5.2.16 on 2026-08-12 15:05

import controlled_vocabularies.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabularies', '0007_collection_slug_is_manual'),
        ('testapp', '0002_concepts_field_consumers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borehole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The borehole's catalogue name.", max_length=255, verbose_name='name')),
                ('dominant_material', controlled_vocabularies.fields.ConceptField(blank=True, help_text='The material logged as dominant, from either the rock-type or the mineral vocabulary.', null=True, related_name='+', verbose_name='dominant material', vocabulary=('rock-type', 'mineral'))),
            ],
        ),
        migrations.CreateModel(
            name='Sketch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The sketch's catalogue name.", max_length=255, verbose_name='name')),
                ('subject', controlled_vocabularies.fields.ConceptField(blank=True, help_text="The sketch's subject, drawn from any vocabulary; this field names none in particular.", null=True, related_name='+', verbose_name='subject', vocabulary=())),
            ],
        ),
    ]
