# Generated by Django 5.2.16 on 2026-08-12 10:27

from django.db import migrations, models

import controlled_vocabularies.fields


class Migration(migrations.Migration):
    dependencies = [
        ("controlled_vocabularies", "0007_collection_slug_is_manual"),
        ("testapp", "0002_concepts_field_deposit_survey"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="The field note's catalogue name.", max_length=255, verbose_name="name"),
                ),
                (
                    "keywords",
                    controlled_vocabularies.fields.ConceptsField(
                        blank=True,
                        help_text="Keywords drawn from either the rock-type or the mineral vocabulary.",
                        related_name="+",
                        verbose_name="keywords",
                        vocabulary=("rock-type", "mineral"),
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Outcrop",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="The outcrop's catalogue name.", max_length=255, verbose_name="name"),
                ),
                (
                    "minerals",
                    controlled_vocabularies.fields.ConceptsField(
                        blank=True,
                        help_text="The minerals observed at this outcrop, if any.",
                        related_name="outcrops",
                        verbose_name="minerals",
                        vocabulary=("mineral",),
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Photograph",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="The photograph's catalogue name.", max_length=255, verbose_name="name"),
                ),
                (
                    "keywords",
                    controlled_vocabularies.fields.ConceptsField(
                        blank=True,
                        help_text="Keywords drawn from any vocabulary; this field names none in particular.",
                        related_name="+",
                        verbose_name="keywords",
                        vocabulary=(),
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RockSample",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="The rock sample's catalogue name.", max_length=255, verbose_name="name"
                    ),
                ),
                (
                    "associated_minerals",
                    controlled_vocabularies.fields.ConceptsField(
                        blank=True,
                        help_text="Any additional minerals observed in this sample.",
                        related_name="+",
                        verbose_name="associated minerals",
                        vocabulary=("mineral",),
                    ),
                ),
                (
                    "primary_mineral",
                    controlled_vocabularies.fields.ConceptField(
                        blank=True,
                        help_text="The single mineral this sample is primarily classified as, if known.",
                        null=True,
                        verbose_name="primary mineral",
                        vocabulary="mineral",
                    ),
                ),
            ],
        ),
    ]
