# Generated by Django 5.2.16 on 2026-08-14 06:41

import django.db.models.deletion
from django.db import migrations, models

import controlled_vocabularies.fields


class Migration(migrations.Migration):
    dependencies = [
        ("controlled_vocabularies", "0007_collection_slug_is_manual"),
        ("testapp", "0003_borehole_sketch"),
    ]

    operations = [
        migrations.CreateModel(
            name="Locality",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="The locality's catalogue name.", max_length=255, verbose_name="name"),
                ),
                (
                    "primary_mineral",
                    controlled_vocabularies.fields.ConceptField(
                        blank=True,
                        help_text="The mineral this locality is primarily characterised by, if known.",
                        null=True,
                        related_name="+",
                        verbose_name="primary mineral",
                        vocabulary=("mineral",),
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="specimen",
            name="locality",
            field=models.ForeignKey(
                blank=True,
                help_text="The locality where this specimen was collected, if recorded.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specimens",
                to="testapp.locality",
                verbose_name="locality",
            ),
        ),
    ]
