# Generated by Django 5.2.16 on 2026-08-25 14:01

import controlled_vocabularies.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabularies', '0007_collection_slug_is_manual'),
        ('testapp', '0004_locality_specimen_locality'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The branch sample's catalogue name.", max_length=255, verbose_name='name')),
                ('rock_type', controlled_vocabularies.fields.ConceptField(blank=True, branch='igneous', help_text='The rock type this sample is classified as, drawn from the igneous branch.', null=True, related_name='+', verbose_name='rock type', vocabulary=('rock-type',))),
            ],
        ),
        migrations.CreateModel(
            name='BranchTray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The branch tray's catalogue name.", max_length=255, verbose_name='name')),
                ('rock_types', controlled_vocabularies.fields.ConceptsField(blank=True, branch='igneous', help_text='The rock types logged for this tray, drawn from the igneous branch.', related_name='branch_trays', verbose_name='rock types', vocabulary=('rock-type',))),
            ],
        ),
        migrations.CreateModel(
            name='ChipSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The chip sample's catalogue name.", max_length=255, verbose_name='name')),
                ('rock_type', controlled_vocabularies.fields.ConceptField(blank=True, concepts=('granite', 'basalt'), help_text='The rock type this chip sample is classified as, restricted to granite and basalt.', null=True, related_name='+', verbose_name='rock type', vocabulary=('rock-type',))),
            ],
        ),
        migrations.CreateModel(
            name='ChipTray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The chip tray's catalogue name.", max_length=255, verbose_name='name')),
                ('rock_types', controlled_vocabularies.fields.ConceptsField(blank=True, concepts=('granite', 'basalt'), help_text='The rock types logged for this chip tray, restricted to granite and basalt.', related_name='chip_trays', verbose_name='rock types', vocabulary=('rock-type',))),
            ],
        ),
        migrations.CreateModel(
            name='CoreSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The core sample's catalogue name.", max_length=255, verbose_name='name')),
                ('rock_type', controlled_vocabularies.fields.ConceptField(blank=True, collection='core-samples', help_text='The rock type this core sample is classified as, drawn from the core-samples collection.', null=True, related_name='+', verbose_name='rock type', vocabulary=('rock-type',))),
            ],
        ),
        migrations.CreateModel(
            name='DrillCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The drill core's catalogue name.", max_length=255, verbose_name='name')),
                ('rock_types', controlled_vocabularies.fields.ConceptsField(blank=True, collection='core-samples', help_text='The rock types logged for this drill core, drawn from the core-samples collection.', related_name='drill_cores', verbose_name='rock types', vocabulary=('rock-type',))),
            ],
        ),
    ]
