# Generated by Django 5.2.16 on 2026-08-25 11:59

import controlled_vocabularies.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabularies', '0007_collection_slug_is_manual'),
        ('testapp', '0004_locality_specimen_locality'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The core sample's catalogue name.", max_length=255, verbose_name='name')),
                ('rock_type', controlled_vocabularies.fields.ConceptField(blank=True, collection='core-samples', help_text='The rock type this core sample is classified as, drawn from the core-samples collection.', null=True, related_name='+', verbose_name='rock type', vocabulary=('rock-type',))),
            ],
        ),
        migrations.CreateModel(
            name='DrillCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The drill core's catalogue name.", max_length=255, verbose_name='name')),
                ('rock_types', controlled_vocabularies.fields.ConceptsField(blank=True, collection='core-samples', help_text='The rock types logged for this drill core, drawn from the core-samples collection.', related_name='drill_cores', verbose_name='rock types', vocabulary=('rock-type',))),
            ],
        ),
    ]
