# Generated by Django 5.2.16 on 2026-08-25 12:19

import controlled_vocabularies.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabularies', '0007_collection_slug_is_manual'),
        ('testapp', '0005_core_sample_drill_core'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChipSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The chip sample's catalogue name.", max_length=255, verbose_name='name')),
                ('rock_type', controlled_vocabularies.fields.ConceptField(blank=True, concepts=('granite', 'basalt'), help_text='The rock type this chip sample is classified as, restricted to granite and basalt.', null=True, related_name='+', verbose_name='rock type', vocabulary=('rock-type',))),
            ],
        ),
        migrations.CreateModel(
            name='ChipTray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The chip tray's catalogue name.", max_length=255, verbose_name='name')),
                ('rock_types', controlled_vocabularies.fields.ConceptsField(blank=True, concepts=('granite', 'basalt'), help_text='The rock types logged for this chip tray, restricted to granite and basalt.', related_name='chip_trays', verbose_name='rock types', vocabulary=('rock-type',))),
            ],
        ),
    ]
