# Generated by Django 5.2.16 on 2026-08-25 12:45

import controlled_vocabularies.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabularies', '0007_collection_slug_is_manual'),
        ('testapp', '0006_chip_sample_chip_tray'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The branch sample's catalogue name.", max_length=255, verbose_name='name')),
                ('rock_type', controlled_vocabularies.fields.ConceptField(blank=True, branch='igneous', help_text='The rock type this sample is classified as, drawn from the igneous branch.', null=True, related_name='+', verbose_name='rock type', vocabulary=('rock-type',))),
            ],
        ),
        migrations.CreateModel(
            name='BranchTray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The branch tray's catalogue name.", max_length=255, verbose_name='name')),
                ('rock_types', controlled_vocabularies.fields.ConceptsField(blank=True, branch='igneous', help_text='The rock types logged for this tray, drawn from the igneous branch.', related_name='branch_trays', verbose_name='rock types', vocabulary=('rock-type',))),
            ],
        ),
    ]
